### ISSUE TITLE
Error fetching Git resource

### ISSUE THREAD

**Issue by miccheng** [concourse/concourse-lite#8]
I tried installing Git as well but ended up having the same issue.

Error message in the web interface:

```
checking failed
resource script '/opt/resource/check []' failed: exit status 128

stderr:
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
fatal: repository '/tmp/git-resource-repo-cache' does not exist
```

The pipeline:

```yaml
---
resources:
  - name: spotlight-git
    type: git
    source:
      url: git@github.com:pivotal-sg/spotlight.git
      branch: master
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        <deploy key>
        -----END RSA PRIVATE KEY-----

jobs:
  - name: spotlight
    plan:
    - get: spotlight-git
      trigger: true
    - task: spotlight-spec
      file: spotlight-git/ci/spotlight-spec.yml
```
